# Name of your workflow
name: Node.js CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Defines a matrix of Node.js versions to test against
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up the specified version of Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Enables caching for npm dependencies to speed up subsequent runs

      # Step 3: Installs project dependencies using 'npm ci'
      # 'npm ci' is recommended for CI as it's faster and uses the package-lock.json for a clean, reliable install
      - name: Install dependencies
        run: npm ci

      # Step 4: Runs your Jest tests using the command defined in your package.json
      - name: Run tests
        run: npm test