# Name of your workflow
name: Node.js CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main", "ci" ] 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci 

      # Run these first as they're faster (unless using an e2e test)
      - name: Run tests
        run: npm test
      
      # Fails if the build process is broken
      - name: Build project 
        run: npm run build  