name: Node.js CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci 

      - name: Create dummy Amplify outputs file
        run: |
          cat > amplify_outputs.json << EOF
          {
            "version": "1",
            "auth": {
              "user_pool_id": "us-east-1_dummy",
              "user_pool_client_id": "dummy_client_id",
              "aws_region": "us-east-1"
            },
            "data": {
              "aws_region": "us-east-1",
              "url": "https://dummy.appsync-api.us-east-1.amazonaws.com/graphql"
            },
            "storage": {
              "aws_region": "us-east-1",
              "bucket_name": "dummy-bucket-name"
            },
            "custom": {
              "API": {
                "bookmarks": {
                  "apiName": "bookmarksApi",
                  "type": "httpApi",
                  "endpoint": "https://dummy.execute-api.us-west-1.amazonaws.com"
                }
              }
            }
          }
          EOF

      # Run these first as they're faster (unless using an e2e test)
      - name: Run tests
        run: npm test
      
      # Fails if the build process is broken
      - name: Build project 
        run: npm run build  